version: '3'
services:
  paddleocr:
    image: gswyhq/paddleocr:2.3.0
    container_name: agitated_mahavira
    command: /bin/bash 
    volumes:
      - ./:/app/PaddleOCR
    tty: true
    stdin_open: true
    working_dir: /app
    entrypoint: ['/bin/bash', '-c', 'pip install -r /app/PaddleOCR/requirements.txt && /bin/bash']
